### ISSUE TITLE
Question: support for related permissions?

### ISSUE THREAD

**Issue by dmarti** [luehrsenheinrich/wpm-floc#10]
Two new, related `Permissions-Policy` permissions have been posted:

 * `join-ad-interest-group`
 * `run-ad-auction`

These do not control FLoC, but affect some related functionality: collecting and running in-browser ad auctions. Are they in scope for this plugin?

The first one defaults to on, but I haven't found the default for the second. Neither one would need to be on for a site that controls all its own JavaScript, but as with FLoC an opt out would protect the site in the event of a third-party (or injected) script attempting to run some ad-related code that the site maintainer is not aware of.

**Source:** [Mention Permissions-Policy directives join-ad-interest-group and run-… · WICG/turtledove@ebd96b8](https://github.com/WICG/turtledove/commit/ebd96b8ce13b26e58dd715251201fbdabffd3af7)

**Comment by Luehrsen** [comment]
I think they are out of scope for this plugin. But thank you for your suggestion! 

Happy New Year!
